"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['auto_archive.py']
DATA_FILES = []
PLIST = {
    'CFBundleShortVersionString': '0.0.1',
    'CFBundleGetInfoString': 'AutoArchive 0.0.1',
    'CFBundleIdentifier': 'net.extrawdw.AutoArchive',
    'NSHumanReadableCopyright': 'Copyright © 2023 Dingwen Wang. All rights reserved.',
}
OPTIONS = {
    'iconfile': '/System/Library/CoreServices/CoreTypes.bundle/Contents/Resources/AllMyFiles.icns',
    'plist': PLIST,
}

setup(
    app=APP,
    name='AutoArchive',
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
